// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain
#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
Texture2D<float4> Result;
AppendStructuredBuffer<int> outFootTexIndex;
float3 pos[64];
int trueCount;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
   
   for(int i=0;i<trueCount;i++)
   {   
      float x=pos[i].x; float y=pos[i].y;
      if(id.x==x&&id.y==y)
      {
         int stepValue=1-step(Result[id.xy].z,0);

         int num5=step(0.9,Result[id.xy].z);
         int num4=step(0.7,Result[id.xy].z);
         int num3=step(0.5,Result[id.xy].z);
         int num2=step(0.3,Result[id.xy].z);
         int num1=step(0.1,Result[id.xy].z); 
         
         int step4=(1-num5)*num4;
         int step3=(1-step4)*num3;
         int step2=(1-step3)*num2;
         int step1=(1-step2)*num1;

         int resultValue=5*num5+4*step4+3*step3+2*step2+step1; 
         outFootTexIndex.Append(resultValue);
       
      }
   }

  
}
