// <auto-generated>
// Generated from InputActionAsset. Do not edit manually.
// </auto-generated>

public static class GamepadControlsNameData
{
    public const string gameplay_movement = "movement";
    public const string gameplay_button1Action = "button1Action";
    public const string gameplay_button2Action = "button2Action";
}
