// <auto-generated>
// Generated from InputActionAsset. Do not edit manually.
// </auto-generated>

public static class PointerControlsNameData
{
    public const string pointer_point = "point";
}
