// <auto-generated>
// Generated from InputActionAsset. Do not edit manually.
// </auto-generated>

public static class InputSystem_ActionsNameData
{
    public const string Player_Move = "Move";
    public const string Player_Look = "Look";
    public const string Player_Attack = "Attack";
    public const string Player_Interact = "Interact";
    public const string Player_Crouch = "Crouch";
    public const string Player_Jump = "Jump";
    public const string Player_Previous = "Previous";
    public const string Player_Next = "Next";
    public const string Player_Sprint = "Sprint";
    public const string UI_Navigate = "Navigate";
    public const string UI_Submit = "Submit";
    public const string UI_Cancel = "Cancel";
    public const string UI_Point = "Point";
    public const string UI_Click = "Click";
    public const string UI_RightClick = "RightClick";
    public const string UI_MiddleClick = "MiddleClick";
    public const string UI_ScrollWheel = "ScrollWheel";
    public const string UI_TrackedDevicePosition = "TrackedDevicePosition";
    public const string UI_TrackedDeviceOrientation = "TrackedDeviceOrientation";
}
