// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
Texture2D<float4> Result;
AppendStructuredBuffer<float4> outColor;
float2 uv[8];

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
   for(int i=0;i<8;i++)
   { 
      float x=uv[i].x; float y=uv[i].y;
      if(id.x==x&&id.y==y)
      {
         outColor.Append(Result[id.xy]);
      }
   }

   // if(id.x==uv.x&&id.y==uv.y)
   // {
   //    outColor.Append(Result[id.xy]);
   // }
    // TODO: insert actual code here!
   

   // Result[id.xy] = float4(id.x & id.y, (id.x & 15)/15.0, (id.y & 15)/15.0, 0.0);
}
