using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;
using UnityEngine.InputSystem;

public sealed class InputActionNameDataGenerator : AssetPostprocessor
{
    const string InputActionExtension = ".inputactions";

    static void OnPostprocessAllAssets(string[] importedAssets, string[] deletedAssets, string[] movedAssets, string[] movedFromAssetPaths)
    {
        foreach (string assetPath in importedAssets)
            GenerateIfInputActionAsset(assetPath);

        foreach (string assetPath in movedAssets)
            GenerateIfInputActionAsset(assetPath);
    }

    [MenuItem("Tools/Input System/Generate Input Name Data")]
    public static void GenerateAll()
    {
        string[] guids = AssetDatabase.FindAssets("t:InputActionAsset");
        foreach (string guid in guids)
            GenerateIfInputActionAsset(AssetDatabase.GUIDToAssetPath(guid));

        AssetDatabase.Refresh();
    }

    static void GenerateIfInputActionAsset(string assetPath)
    {
        if (string.IsNullOrEmpty(assetPath) || Path.GetExtension(assetPath) != InputActionExtension)
            return;

        var inputActionAsset = AssetDatabase.LoadAssetAtPath<InputActionAsset>(assetPath);
        if (inputActionAsset == null)
            return;

        string outputPath = Path.ChangeExtension(assetPath, null) + "NameData.cs";
        string className = SanitizeIdentifier(Path.GetFileNameWithoutExtension(assetPath) + "NameData");
        string content = GenerateCode(inputActionAsset, className);

        if (File.Exists(outputPath) && File.ReadAllText(outputPath) == content)
            return;

        File.WriteAllText(outputPath, content, Encoding.UTF8);
        AssetDatabase.ImportAsset(outputPath, ImportAssetOptions.ForceUpdate);
    }

    static string GenerateCode(InputActionAsset inputActionAsset, string className)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated>");
        builder.AppendLine("// Generated from InputActionAsset. Do not edit manually.");
        builder.AppendLine("// </auto-generated>");
        builder.AppendLine();
        builder.Append("public static class ");
        builder.AppendLine(className);
        builder.AppendLine("{");

        foreach (InputActionMap actionMap in inputActionAsset.actionMaps)
        {
            foreach (InputAction action in actionMap.actions)
            {
                builder.Append("    public const string ");
                builder.Append(SanitizeIdentifier($"{actionMap.name}_{action.name}"));
                builder.Append(" = ");
                builder.Append(ToStringLiteral(action.name));
                builder.AppendLine(";");
            }
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    static string SanitizeIdentifier(string value)
    {
        if (string.IsNullOrEmpty(value))
            return "_";

        var builder = new StringBuilder(value.Length);
        char first = value[0];
        builder.Append(char.IsLetter(first) || first == '_' ? first : '_');

        for (int i = 1; i < value.Length; i++)
        {
            char c = value[i];
            builder.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
        }

        return builder.ToString();
    }

    static string ToStringLiteral(string value)
    {
        return "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
    }
}
